### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by goodGid** [volantis-x/hexo-theme-volantis#159]
I want to apply this theme but I got an error. I do not know what should I do

---

我想应用此主题，但出现错误。 我不知道该怎么办

<img width="740" alt="Screen Shot 2020-03-04 at 9 50 07 AM" src="https://user-images.githubusercontent.com/18522341/75833878-b13e9880-5dfd-11ea-8771-b483f25e2413.png">

**Comment by Reqwey** [comment]
테마를 수정하지 않으면 테마 자체에이 명백한 문제가 발생하지 않습니다. Hexo 버전이 너무 낮아서 버전 4.2.0으로 업그레이드 한 후 다시 시도하는 것이 좋습니다.

-----

Hello, the theme itself will not have this obvious problem if it is not modified. It may be because your Hexo version is too low. It is recommended to upgrade to version 4.2.0 and try again

-----

你好, 主题本身如果不做修改是不会有这种明显的问题. 可能是由于你的Hexo版本过低. 建议升级至 version 4.2.0 后再试

**Comment by xaoxuu** [comment]
It's a bug...

**Comment by xaoxuu** [comment]
看报错信息，`theme.widget`是`undefined`，于是我创建个新项目看看确实这个报错。。

**Comment by Reqwey** [comment]
> 看报错信息，`theme.widget`是`undefined`，于是我创建个新项目看看确实这个报错。。

哈哈哈

-----

ha ha ha

**Comment by xaoxuu** [comment]
I fixed this bug in `1.7.3`: https://github.com/xaoxuu/hexo-theme-volantis/releases/tag/1.7.3

**Comment by goodGid** [comment]
@Linhk1606 
Hello 
i want to contact you for your Blog
Can you tell me your email address?
Thank you !

**Comment by Reqwey** [comment]
Of course you can.

Outlook: Linhk1606@outlook.com

Gmail: LHKSTUDIO2020@gmail.com

**Comment by goodGid** [comment]
@Linhk1606 
Thank you for quick response ! 
I will send email via gmail
